### ISSUE TITLE
which cuda card?

### ISSUE THREAD

**Issue by galenthegeometer** [JonnoFTW/htm-cl#1]
Hey, Jonno, which cuda card are you using?  It is important to know. 

It s also important to know which motherboard and CPU you are using.  For instance, I am thinking of building a workstation with dual Xeon E5's, since I need a lot of cores for graphical design.  On e-Bay, you can get used E5's for $50 each, and that's a big savings over an i5 or i7 motherboard.

But the question is, do those extra cores, in combination with openCL, speed up things synergetically?

**Comment by JonnoFTW** [comment]
Just to clarify, cuda only runs on NVIDIA cards, opencl runs on NVIDIA and
AMD cards along with other platforms like the Intel Xeon Phi. I picked
opencl because it can run on a larger number of devices (I also don't know
cuda). That said I'll test my implementation on my AMD R9 380 and my
workstation GPU (I don't recall the specific model). I'll also test it on a
NVIDIA K20M. I feel such a range of devices should cover the full range of
GPU devices from standard workstation, home gaming, and high performance
computing.

As for whether it provides significant performance improvements remains to
be seen since I've yet to implement the major algorithms in htm, I've been
on holidays for the past few weeks so work has slowed down but I'll pick up
work now that I'm back.

**Comment by galenthegeometer** [comment]
The language CUDA is a subset of C, like you say, it only works on Nvidia.

Watch out using these cards, they suck up the watts.  One can brown out your motherboard, you need a big power supply.

HTM has a lot of calculation, I mean a whole lot.  Some way needs to be found to trim that down.  I’m thinking hard about that.

Don’t assume that any card will run CUDA or openCL, check first.  Some of the older ones won’t.  And there are differences in the card’s compute capability.  Here’s the link showing the relative capabilities of Nvidia cards (this is for running CUDA, but it should be equivalent running openCL):   CUDA GPUs | NVIDIA Developer <https://developer.nvidia.com/cuda-gpus>.   I wasn’t able to find anything about AMD’s products.  It’s probably out there, hidden.


—————————

Jesse Johnson
puppetistas@gmail.com

**Comment by JonnoFTW** [comment]
CUDA only runs on NVIDIA products, which is why I am using OpenCL. OpenCL runs on many NVIDIA products an AMD products, so I chose opencl to ensure that the most people can use this project regardless of what card they have.
